sudo: required
services:
  - docker

before_install:
  - docker build -t robperch/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run robperch/react-test npm test -- -- coverage

after_success:
  - docker build -t robperch/multi-client ./client
  - docker build -t robperch/multi-nginx ./nginx
  - docker build -t robperch/multi-server ./server
  - docker build -t robperch/multi-worker ./worker
  # Log to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push robperch/multi-client 
  - docker push robperch/multi-nginx 
  - docker push robperch/multi-server 
  - docker push robperch/multi-worker
